# Specify filenames of default patillavatar pics located at /web/static/pics.
patillavatars = [ "default.jpg", "default2.jpg" ]
# Specify the absolute path to the folder where files will be uploaded.
upload_dir = "C:/Users/USER/Documents/gopath/src/github.com/luisguve/cherosite/tmp"
# Specify the absolute path to the folder where static files are be stored in.
static_dir = "C:/Users/USER/Documents/gopath/src/github.com/luisguve/cherosite/web/static"
# Specify the absolute path to the folder where the templates for internal use are stored in.
internal_tpl_dir = "C:/Users/USER/Documents/gopath/src/github.com/luisguve/cherosite/web/internal/templates"
# Specify the absolute path to the folder where the templates for page rendering are stored in.
public_tpl_dir = "C:/Users/USER/Documents/gopath/src/github.com/luisguve/cherosite/web/templates"

# Set the id, name and bind address of every section. See cheroapi repo.
[[sections]]
  id = "mylife" # It will match the section id in URLs.
  name = "My Life"
  bind_address = "localhost:50053"

# Sessions are handled with cookies through gorilla/sessions in a file system store.
[session_variables]
  # Specify the absolute path for the folder where the sessions will be stored in.
  sess_dir = "C:/cherosite_files/sess"
  # This must be kept in secret. This was generated by GenerateRandomKey from
  # gorilla/securecookie.
  sess_secret_key = "√Æ√ß|√É√â¬π7√†‚ÄôÀú‚Ç¨‚Äù√å√•√≠√¢8¬≤√éy3N‚Äî√åZ¬¨i√¥/r"

[http_config]
  bind_address = "127.0.0.1" # It could also be "localhost".
  port = "8000"

# Set the bind address for the users and general services. See cheroapi repo.
[services]
  [services.users]
  bind_address = "localhost:50051"
  [services.general]
  bind_address = "localhost:50052"
